# Generated by Django 5.0.8 on 2026-04-15 14:36

import django.db.models.deletion
import expenses.models
import expenses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_expense_category_xor_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=expenses.models.attachment_upload_path, validators=[expenses.validators.validate_attachment])),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=128)),
                ('size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='expenses.expense')),
            ],
        ),
    ]
