# Generated by Django 5.0.8 on 2026-04-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='source',
            field=models.CharField(choices=[('admin', 'Админ'), ('employee', 'Сотрудник')], default='admin', max_length=16),
        ),
    ]
